apiVersion: v1
kind: Pod
metadata:
  name: multus-only-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-confifg",
              "ips": [ "10.1.1.101/24" ],
              "mac": "c2:b0:57:49:47:f1"
            }]'
spec:
  containers:
  - name: multus-only-pod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: ra77us/suu:1.0.0
    ports:
    - containerPort: 80