FROM ubuntu:20.04

RUN apt-get -qq update \
  && apt-get -qq install --no-install-recommends \
       ca-certificates \
       wget \
       xz-utils \
       net-tools \
       pciutils \
       iproute2 \
       sudo \
       ethtool \
       lshw \
       macchanger \
       iputils-ping \
